import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<Uint8List> buildReport({
    required List<Map<String, dynamic>> data,
    required String insight,
    required String reportTitle,
    required String reportType,
    Uint8List? bpmGraph,
    Uint8List? spo2Graph,
    Uint8List? tempGraph,
  }) async {
    final pdf = pw.Document();

    final logo = await rootBundle.load('assets/images/logo.png');
    final logoBytes = logo.buffer.asUint8List();

    final now = DateTime.now();
    final date = '${now.day}/${now.month}/${now.year}';
    final time =
        '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}';
    final day = [
      'Mon',
      'Tue',
      'Wed',
      'Thu',
      'Fri',
      'Sat',
      'Sun',
    ][now.weekday - 1];

    final last = data.isNotEmpty ? data.last : null;
    final first = data.isNotEmpty ? data.first : null;

    final bpm = last != null ? (last['bpm'] as num).toStringAsFixed(0) : '--';
    final spo2 = last != null ? (last['spo2'] as num).toStringAsFixed(0) : '--';
    final temp = last != null ? (last['temp'] as num).toStringAsFixed(1) : '--';
    final typeLabel = _reportTypeLabel(reportType);
    final rangeText = _rangeText(first?['time'], last?['time']);

    final cleanInsight = insight.replaceAll(RegExp(r'[^\x00-\x7F]'), '');
    var insightColor = PdfColors.green;
    var insightBg = PdfColors.green100;

    if (cleanInsight.contains('Low') || cleanInsight.contains('High')) {
      insightColor = PdfColors.red;
      insightBg = PdfColors.red100;
    }

    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(20),
        footer: (context) {
          return pw.Column(
            children: [
              pw.Divider(),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Confidential Health Report',
                    style: pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    'Generated by KineSentry',
                    style: pw.TextStyle(fontSize: 9),
                  ),
                ],
              ),
            ],
          );
        },
        build: (context) {
          return [
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#0A0F1C'),
                borderRadius: pw.BorderRadius.circular(10),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Row(
                    children: [
                      pw.Container(
                        height: 52,
                        width: 52,
                        padding: const pw.EdgeInsets.all(6),
                        decoration: pw.BoxDecoration(
                          color: PdfColors.white,
                          borderRadius: pw.BorderRadius.circular(8),
                        ),
                        child: pw.Image(pw.MemoryImage(logoBytes)),
                      ),
                      pw.SizedBox(width: 12),
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            'KineSentry',
                            style: pw.TextStyle(
                              color: PdfColors.white,
                              fontSize: 20,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                          pw.Text(
                            'Health Monitoring Report',
                            style: pw.TextStyle(
                              color: PdfColors.grey300,
                              fontSize: 11,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Container(
                        padding: const pw.EdgeInsets.symmetric(
                          horizontal: 10,
                          vertical: 5,
                        ),
                        decoration: pw.BoxDecoration(
                          color: _reportTypeColor(reportType),
                          borderRadius: pw.BorderRadius.circular(6),
                        ),
                        child: pw.Text(
                          typeLabel.toUpperCase(),
                          style: pw.TextStyle(
                            color: PdfColors.white,
                            fontSize: 9,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                      ),
                      pw.SizedBox(height: 8),
                      pw.Text(
                        '$date ($day)',
                        style: pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 10,
                        ),
                      ),
                      pw.Text(
                        time,
                        style: pw.TextStyle(
                          color: PdfColors.grey300,
                          fontSize: 10,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#F4F7FB'),
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: PdfColor.fromHex('#D0D5DD')),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    reportTitle,
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColor.fromHex('#0D1117'),
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    '$typeLabel report | $rangeText | ${data.length} readings',
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: PdfColor.fromHex('#475467'),
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 18),
            pw.Text(
              'Vitals Snapshot',
              style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            pw.Row(
              children: [
                _summaryCard('Heart Rate', '$bpm BPM', PdfColors.red),
                pw.SizedBox(width: 10),
                _summaryCard('SpO2', '$spo2%', PdfColors.blue),
                pw.SizedBox(width: 10),
                _summaryCard('Temperature', '$temp C', PdfColors.orange),
              ],
            ),
            pw.SizedBox(height: 22),
            if (data.length >= 2) ...[
              _sectionTitle('Vital Trend Graphs'),
              pw.SizedBox(height: 10),
              _vitalChartBlock(
                title: 'Heart Rate',
                unit: 'BPM',
                data: data,
                key: 'bpm',
                color: PdfColors.red,
                minY: 50,
                maxY: 140,
              ),
              _vitalChartBlock(
                title: 'SpO2',
                unit: '%',
                data: data,
                key: 'spo2',
                color: PdfColors.blue,
                minY: 85,
                maxY: 100,
              ),
              _vitalChartBlock(
                title: 'Temperature',
                unit: 'C',
                data: data,
                key: 'temp',
                color: PdfColors.orange,
                minY: 34,
                maxY: 40,
              ),
              pw.SizedBox(height: 20),
            ] else ...[
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(
                  'Vital trend graphs need at least two readings.',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ),
              pw.SizedBox(height: 20),
            ],
            _sectionTitle('Insights & Recommendations'),
            pw.SizedBox(height: 10),
            pw.Container(
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: insightBg,
                borderRadius: pw.BorderRadius.circular(12),
                border: pw.Border.all(color: insightColor, width: 2),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    cleanInsight,
                    style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      lineSpacing: 2,
                    ),
                  ),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static Future<void> generateReport({
    required List<Map<String, dynamic>> data,
    required String insight,
    required String reportTitle,
    required String reportType,
    Uint8List? bpmGraph,
    Uint8List? spo2Graph,
    Uint8List? tempGraph,
  }) async {
    final bytes = await buildReport(
      data: data,
      insight: insight,
      reportTitle: reportTitle,
      reportType: reportType,
      bpmGraph: bpmGraph,
      spo2Graph: spo2Graph,
      tempGraph: tempGraph,
    );

    await Printing.layoutPdf(onLayout: (format) async => bytes);
  }

  static Future<void> viewReport(Uint8List bytes) async {
    await Printing.layoutPdf(onLayout: (format) async => bytes);
  }

  static Future<void> downloadReport(Uint8List bytes, String filename) async {
    await Printing.sharePdf(bytes: bytes, filename: filename);
  }

  static pw.Widget _summaryCard(String label, String value, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromHex('#F9FAFB'),
          borderRadius: pw.BorderRadius.circular(8),
          border: pw.Border.all(color: PdfColor.fromHex('#D0D5DD')),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 9,
                color: PdfColor.fromHex('#667085'),
              ),
            ),
            pw.SizedBox(height: 6),
            pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 15,
                fontWeight: pw.FontWeight.bold,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Row(
      children: [
        pw.Container(
          height: 14,
          width: 4,
          decoration: pw.BoxDecoration(
            color: PdfColor.fromHex('#2563EB'),
            borderRadius: pw.BorderRadius.circular(2),
          ),
        ),
        pw.SizedBox(width: 8),
        pw.Text(
          text,
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  static pw.Widget _vitalChartBlock({
    required String title,
    required String unit,
    required List<Map<String, dynamic>> data,
    required String key,
    required PdfColor color,
    required double minY,
    required double maxY,
  }) {
    final chartData = data.asMap().entries.map((entry) {
      return pw.PointChartValue(
        entry.key.toDouble(),
        (entry.value[key] ?? 0).toDouble(),
      );
    }).toList();

    final lastIndex = (data.length - 1).toDouble();
    final middleIndex = (lastIndex / 2).roundToDouble();
    final xValues = _uniqueSorted([0.0, middleIndex, lastIndex]);
    final yValues = _uniqueSorted([minY, (minY + maxY) / 2, maxY]);

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 14),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: .7),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            '$title ($unit)',
            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.SizedBox(
            height: 135,
            child: pw.Chart(
              grid: pw.CartesianGrid(
                xAxis: pw.FixedAxis(
                  xValues,
                  divisions: true,
                  divisionsColor: PdfColors.grey300,
                  textStyle: const pw.TextStyle(fontSize: 7),
                  format: (value) => _timeLabel(data[value.toInt()]['time']),
                ),
                yAxis: pw.FixedAxis(
                  yValues,
                  divisions: true,
                  divisionsColor: PdfColors.grey300,
                  textStyle: const pw.TextStyle(fontSize: 8),
                  format: (value) =>
                      value.toStringAsFixed(key == 'temp' ? 1 : 0),
                ),
              ),
              datasets: [
                pw.LineDataSet(
                  data: chartData,
                  color: color,
                  lineWidth: 2,
                  drawPoints: chartData.length <= 30,
                  pointSize: 2,
                  drawSurface: true,
                  surfaceOpacity: .12,
                  isCurved: true,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static List<double> _uniqueSorted(List<double> values) {
    return values.toSet().toList()..sort();
  }

  static String _reportTypeLabel(String type) {
    if (type == 'session') return 'Session';
    if (type == 'daily') return 'Daily';
    return 'Hourly';
  }

  static PdfColor _reportTypeColor(String type) {
    if (type == 'session') return PdfColors.cyan;
    if (type == 'daily') return PdfColors.green;
    return PdfColors.blue;
  }

  static String _rangeText(dynamic rawStart, dynamic rawEnd) {
    if (rawStart is! DateTime || rawEnd is! DateTime) {
      return 'No time range available';
    }

    return '${_dateTimeLabel(rawStart)} - ${_dateTimeLabel(rawEnd)}';
  }

  static String _dateTimeLabel(DateTime time) {
    final date = '${time.day}/${time.month}/${time.year}';
    final clock =
        '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
    return '$date $clock';
  }

  static String _timeLabel(dynamic rawTime) {
    final time = rawTime is DateTime ? rawTime : DateTime.now();
    return '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
  }
}
