// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCavQSnikdB0hrns5Sz3sE6KQjeS4UAAB0',
    appId: '1:982090943295:web:d4c335a3d878563c06218a',
    messagingSenderId: '982090943295',
    projectId: 'kinesentry-77c9a',
    authDomain: 'kinesentry-77c9a.firebaseapp.com',
    storageBucket: 'kinesentry-77c9a.firebasestorage.app',
    measurementId: 'G-9VMW5ZFQ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZllG6TT1hOUjuKWcgR5UEp9G4tdLXSyo',
    appId: '1:982090943295:android:f6bc5803dcbbc58206218a',
    messagingSenderId: '982090943295',
    projectId: 'kinesentry-77c9a',
    storageBucket: 'kinesentry-77c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj00jXJPcNNcyEyB_AIhaIb28fPlUvDP8',
    appId: '1:982090943295:ios:f5f344f77092c1e906218a',
    messagingSenderId: '982090943295',
    projectId: 'kinesentry-77c9a',
    storageBucket: 'kinesentry-77c9a.firebasestorage.app',
    iosBundleId: 'com.example.kinesentry1App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj00jXJPcNNcyEyB_AIhaIb28fPlUvDP8',
    appId: '1:982090943295:ios:f5f344f77092c1e906218a',
    messagingSenderId: '982090943295',
    projectId: 'kinesentry-77c9a',
    storageBucket: 'kinesentry-77c9a.firebasestorage.app',
    iosBundleId: 'com.example.kinesentry1App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCavQSnikdB0hrns5Sz3sE6KQjeS4UAAB0',
    appId: '1:982090943295:web:1b7e608020a73b9d06218a',
    messagingSenderId: '982090943295',
    projectId: 'kinesentry-77c9a',
    authDomain: 'kinesentry-77c9a.firebaseapp.com',
    storageBucket: 'kinesentry-77c9a.firebasestorage.app',
    measurementId: 'G-ZPXEWQLYXN',
  );
}
